import { spawn } from 'node:child_process';
import { readFileSync, accessSync, constants, realpathSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodeMessage, createDecoder } from '../native/protocol.mjs';

// Keep stdin open until a reply: closing it immediately tells host.mjs to cancel
// the Codex connection, which would turn this diagnostic into a false failure.
export function probeHost({ command, args = [], cwd, env = process.env, timeoutMs = 20000 }) {
  return new Promise(resolve => {
    let stderr = '', response, failure = '', done = false;
    const child = spawn(command, args, { cwd, env, windowsHide: true, stdio: ['pipe', 'pipe', 'pipe'] });
    const finish = (code, signal) => {
      if (done) return;
      done = true; clearTimeout(timer);
      resolve({ response, failure, exitCode: code, signal, stderr: stderr.trim() });
    };
    const timer = setTimeout(() => { failure = '等待本地程序回复超时。'; child.stdin.end(); child.kill(); finish(null, 'timeout'); }, timeoutMs);
    const decode = createDecoder(message => {
      if (message.id !== 'doctor-host') return;
      response = message;
      child.stdin.end();
    });
    child.stdout.on('data', chunk => {
      try { decode(chunk); }
      catch (error) { failure = `本地程序输出格式错误：${error.message}`; child.stdin.end(); }
    });
    child.stderr.setEncoding('utf8');
    child.stderr.on('data', chunk => { stderr = (stderr + chunk).slice(-12000); });
    child.stdin.on('error', () => {});
    child.on('error', error => { failure = `无法启动：${error.message}`; finish(null, null); });
    child.on('close', (code, signal) => finish(code, signal));
    child.stdin.write(encodeMessage({ id: 'doctor-host', type: 'status' }));
  });
}

async function main() {
  const root = fileURLToPath(new URL('../', import.meta.url));
  console.log(`Node: ${process.version}`);
  console.log(`项目: ${root}`);
  if (process.platform !== 'darwin') throw new Error('此命令用于诊断 macOS 浏览器的本地程序启动。');
  const channel = process.argv[2] || 'chrome';
  const browsers = { chrome: 'Google/Chrome', edge: 'Microsoft Edge', chromium: 'Chromium' };
  if (!browsers[channel]) throw new Error('参数为 chrome、edge 或 chromium。');
  const manifestFile = path.join(homedir(), 'Library', 'Application Support', browsers[channel], 'NativeMessagingHosts', 'com.local.youtube_luna.json');
  console.log(`登记文件: ${manifestFile}`);
  const manifest = JSON.parse(readFileSync(manifestFile, 'utf8'));
  const expected = path.join(root, '.local', 'native-host.sh');
  console.log(`启动脚本: ${manifest.path}`);
  if (manifest.path !== expected) console.log(`注意：浏览器指向的不是本项目启动脚本，当前项目应为 ${expected}`);
  accessSync(manifest.path, constants.X_OK);
  // This file is generated by our installer and contains executable paths, not credentials.
  console.log(`启动脚本内容:\n${readFileSync(manifest.path, 'utf8').trim()}`);
  const result = await probeHost({ command: manifest.path,
    args: ['chrome-extension://aeofkpgbodbdljhlibnnhbjkalpjenid/'], cwd: path.dirname(manifest.path),
    env: { ...process.env, PATH: '/usr/bin:/bin:/usr/sbin:/sbin' } });
  console.log(`退出码: ${result.exitCode ?? '无'}${result.signal ? ` (${result.signal})` : ''}`);
  if (result.stderr) console.log(`错误输出:\n${result.stderr}`);
  if (result.failure) console.log(result.failure);
  if (!result.response) {
    process.exitCode = 1;
    console.log('未收到本地通信回复：故障发生在启动脚本或 host.mjs 阶段。');
    if (result.exitCode === 0 && !result.stderr) console.log('程序正常退出但没有回复，请检查项目路径是否经过符号链接。');
  } else if (!result.response.ok) {
    process.exitCode = 1;
    console.log(`本地通信已接通，但 Codex 连接失败：${result.response.error}`);
  } else {
    console.log(`本地通信已接通：${result.response.result?.message}`);
    if (!result.response.result?.loggedIn) process.exitCode = 1;
    console.log('此结果只验证终端启动链路；若浏览器仍失败，需要继续检查浏览器的文件访问权限或它使用的登记路径。');
  }
}

if (process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  main().catch(error => { console.error(error.message); process.exitCode = 1; });
}
